"""Remove is_active, is_superuser, is_verified columns

Revision ID: 1dd985b54675
Revises: e4d36abb1dbc
Create Date: 2025-12-12 14:11:13.141279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd985b54675'
down_revision: Union[str, Sequence[str], None] = 'e4d36abb1dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
